### ISSUE TITLE
Wish: More flexible deferred:url-post function.

### ISSUE THREAD

**Issue by boyw165** [kiwanami/emacs-deferred#34]
This is an excellent library.
When I'm trying to create a POST command with raw format in the data field. It won't let me do this because following code in the `deferred:url-post`:
```
(url-request-data (deferred:url-param-serialize params))
```
> e.g. I need to fill in the data field with a JSON object.

So I'm currently using `deferred:url-retrieve` to complete my mission.
It would be very nice if the API is more generic. :D

**Comment by kiwanami** [comment]
Hi @boyw165 

`deferred:url-post` is very simple shortcut function, not for general purpose. When I implemented `deferred.el` in 2010, I thought the `url` library is not good, because it had many problems around SSL, proxy connections and Windows environment. (Currently, I believe it may be fixed...)

I recommend the great library [request.el](https://github.com/tkf/emacs-request) for general purpose. It has `deferred.el` adapter `request-deferred`. It seems to pass string raw content at the `DATA` field to the request body of POST command.

**Comment by boyw165** [comment]
Thank you @kiwanami . :D
